# 生产环境配置
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soical001?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: productionPassword
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      
  # SpringFox配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 日志配置
logging:
  level:
    com.soical.server: info
    org.springframework: warn
  file:
    name: logs/soical.log
    max-size: 100MB
    max-history: 30 